[package]
name = "glauncher"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.26.2"
crossterm = "0.27.0"
serde = { version = "1.0.202", features = ["derive"] }
toml = "0.8.13"
dirs = "5.0.1"
